version: '3.5'

services:
    laravel-app:
        build:
            context: '.'
        container_name: app
        depends_on:
            - mariadb
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        stdin_open: true

        environment:
            - "DB_PASSWORD=securerootpassword"
            - "DB_HOST=db"
            - "REDIS_HOST=redis"
        tty: true
        ports:
            - 8083:80
        networks:
            backend:
                aliases:
                    - app

    mariadb:
        image: mariadb:10.2.26
        container_name: app-db
        volumes:
            - ./run/var:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=securerootpassword
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=securerootpassword
        ports:
            - 3309:3306
        networks:
            backend:
                aliases:
                    - db

    redis:
        container_name: app-redis
        image: redis:4.0
        ports:
            - 6382:6379
        networks:
            backend:
                aliases:
                    - redis

networks:
    backend:
        name: backend-network
